CREATE TABLE edxapp.question_template (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	xblock_id VARCHAR(255) NOT NULL,
	template VARCHAR(2048) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=40;

CREATE TABLE edxapp.variable (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	template_id INT(6) UNSIGNED,
	name VARCHAR(32),
	type VARCHAR(32),
	min_value INT(6),
	max_value INT(6),
	FOREIGN KEY (template_id) REFERENCES edxapp.question_template(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=40;

CREATE TABLE edxapp.expression (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	template_id INT(6) UNSIGNED,
	value VARCHAR(2048) NOT NULL,
	FOREIGN KEY (template_id) REFERENCES edxapp.question_template(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=40;